export const characterConstants = {
	CHARACTERS_REQUEST: 'CHARACTERS_REQUEST',
    CHARACTERS_SUCCESS: 'GET_CHARACTERS_SUCCESS',
    CHARACTERS_FAILURE: 'GET_CHARACTERS_FAILURE',

    CREATE_CHARACTERS_REQUEST: 'CREATE_CHARACTERS_REQUEST',
    CREATE_CHARACTERS_SUCCESS: 'CREATE_CHARACTERS_SUCCESS',
    CREATE_CHARACTERS_FAILURE: 'CREATE_CHARACTERS_FAILURE'
};